date: '2021-12-13'
sections:
  security_fixes:
    - '{% octicon "alert" aria-label="The alert icon" %} **Crítico:** uma vulnerabilidade de execução de código remoto na biblioteca Log4j, identificada como [CVE-2021-44228](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-44228), afetou todas as versões de {% data variables.product.prodname_ghe_server %} anteriores à 3.3.1. A biblioteca Log4j é usada em um serviço de código aberto sendo executado na instância {% data variables.product.prodname_ghe_server %}. Essa vulnerabilidade foi corrigida nas versões {% data variables.product.prodname_ghe_server %} 3.0.22, 3.1.14, 3.2.6 e 3.3.1.  Para ver mais informações, confira [esta postagem](https://github.blog/2021-12-13-githubs-response-to-log4j-vulnerability-cve-2021-44228/) no Blog do GitHub.'
    - '**Atualização de 17 de dezembro de 2021**: as correções nesta versão também mitigam [CVE-2021-45046](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45046) que foi publicada após esta versão. Não é necessária nenhuma atualização adicional para {% data variables.product.prodname_ghe_server %} mitigar tanto CVE-2021-44228 como CVE-2021-45046.'
  known_issues:
    - "Em uma nova configuração de {% data variables.product.prodname_ghe_server %} sem qualquer usuário, um invasor pode criar o primeiro usuário administrador."
    - As regras de firewall personalizadas são removidas durante o processo de atualização.
    - "Arquivos LFS do Git [enviados através da interface da Web](https://github.com/blog/2105-upload-files-to-your-repositories) são adicionados diretamente ao repositório e de forma incorreta."
    - "Os problemas não podem ser fechados se contiverem um permalink para um blob no mesmo repositório, onde o caminho do arquivo de blobs é maior que 255 caracteres."
    - "Quando \"Usuários podem pesquisar pelo GitHub.com\" está habilitado com o GitHub Connect, os problemas em repositórios privados e internos não estão incluídos nos resultados de pesquisa do GitHub.com."
    - "O registro npm {% data variables.product.prodname_registry %} não retorna mais um valor temporal em respostas de metadados. Isso foi feito para permitir melhorias substanciais de desempenho. Continuamos a ter todos os dados necessários para retornar um valor temporal como parte da resposta de metadados e continuaremos a retornar esse valor no futuro quando tivermos resolvido os problemas de desempenho existentes."
    - Os limites de recursos que são específicos para processamento de hooks pre-receive podem causar falha em alguns hooks pre-receive.
    - '{% data reusables.release-notes.ghas-3.4-secret-scanning-known-issue %}'
