date: '2021-07-14'
sections:
  security_fixes:
    - '**ВЫСОКИЙ.** В GitHub Enterprise Server выявлена уязвимость, связанная с обходом каталога, которую можно было использовать при создании сайта GitHub Pages. Команды управляемой пользователем настройки, используемые GitHub Pages, не имели достаточных ограничений и позволяли считывать файлы в экземпляре GitHub Enterprise. Чтобы эксплуатировать уязвимость, злоумышленнику требовалось разрешение для создания и построения сайта GitHub Pages в экземпляре GitHub Enterprise Server. Эта уязвимость затрагивает все версии GitHub Enterprise Server до 3.1.3, ей присвоен код CVE-2021-22867. Об этой уязвимости сообщается посредством программы GitHub Bug Bounty.'
    - Пакеты обновлены до последних версий систем безопасности.
  bugs:
    - Переменная даты окончания срока действия SAML не подлежит настройке.
    - "Проверка работоспособности служб приложений завершалось ошибкой, если конфигурация применялась до перехода в состояние работоспособности."
    - 'ghe-cluster-config-node-init завершалась ошибкой при настройке кластера, если был включен прокси-сервер HTTP.'
    - "В перехватчиках предварительного получения могла возникать ошибка \"Не удалось разрешить полный путь к текущему исполняемому файлу\" из-за того, что /proc не был присоединен к контейнеру."
    - Collectd не разрешал имя конечного узла переадресации после первоначального запуска.
    - "При выполнении задания, которое выполняло очистку устаревших удаленных репозиториев, могла произойти ошибка, если некоторые репозитории были защищены от удаления законными владельцами."
    - "Фоновые задания помещались в очередь spam, которая не подлежала обработке."
    - Предпочтительный метод объединения сбрасывался при повторной попытке выполнить объединение PR после сбоя первой попытки.
    - "При отправках Git возникала \"Внутренняя ошибка 500 сервера\" в процессе сверки пользователей в экземплярах, для которых используется режим проверки подлинности LDAP."
    - 'После обновления с 3.0.x до 3.1.x в некоторых случаях работа GitHub Actions завершалась сбоем с ошибкой "Произошла непредвиденная ошибка при выполнении этого рабочего потока".'
  changes:
    - "Повышена эффективность применения конфигурации путем пропуска тех правил брандмауэра, определяющих разрешения для IP-адресов, которые не изменялись. Это позволило сэкономить время при работе с большими кластерами."
  known_issues:
    - "Реестр npm {% data variables.product.prodname_registry %} больше не возвращает значение времени в откликах метаданных. Это было сделано, чтобы предусмотреть существенные улучшения производительности. Мы продолжим хранить все данные, необходимые для возврата значения времени в качестве части отклика метаданных и возобновим возврат этого значения в будущем, как только решим существующие проблемы с производительностью."
    - "Злоумышленник мог создать первого пользователя с правами администратора на новом, только что настроенном сервере {% data variables.product.prodname_ghe_server %}, не имеющем пользователей."
    - Пользовательские правила брандмауэра удалены во время процесса обновления.
    - "Отслеженные файлы Git LFS [отправленные через веб-интерфейс](https://github.com/blog/2105-upload-files-to-your-repositories) ошибочно добавлены непосредственно в репозиторий."
    - "Проблемы невозможно закрыть, если они содержат постоянную ссылку на BLOB-объект в том же репозитории, в котором длина пути к файлу BLOB-объекта более 255 символов."
    - "Когда в GitHub Connect включен параметр \"Пользователи могут выполнять поиск на GitHub.com\", результаты поиска на GitHub.com не включают проблемы в частных и внутренних репозиториях."
    - "Если {% data variables.product.prodname_actions %} включен для {% data variables.product.prodname_ghe_server %}, удаление узла реплики с ghe-repl-teardown будет выполнено успешно, но может возвращаться ERROR:Running migrations."
    - "Ограничения ресурсов, относящиеся к обработке перехватчиков предварительного получения могут привести к сбою некоторых из них."
